apiVersion: v1
kind: Service
metadata:
  name: flux-app
spec:
  type: NodePort
  selector:
    app: flux-app
  ports:
    - name: http
      port: 9898
      protocol: TCP
      targetPort: http
    - port: 9999
      targetPort: grpc
      protocol: TCP
      name: grpc
